name: Triage
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write



jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: ilovescratch2/action-auto-issue@main
        with:
          ai-base-url: 	https://api.deepseek.com/v1
          ai-key: ${{ secrets.OPENAI_API_KEY }}
          labels: bug,enhancement,question
          model: 'deepseek-flash'
